### ISSUE TITLE
Does CallMolecularConsensusReads preserve alignment information

### ISSUE THREAD

**Issue by fleharty** [fulcrumgenomics/fgbio#120]
I was recently experimenting with CallMolecularConsensusReads, and it appears to strip the alignment information out of the resulting bam when I use it.  Is this the desired behavior?

**Comment by nh13** [comment]
At present, it is.  @tfenne and myself thought to initially play it safe by removing the alignment information, and thus requiring the consensus reads to be re-aligned as though they were unmapped to begin with.  With some work, it should be possible to emit the correct alignment information, even when the input alignments disagree, are trimmed differently, have different indel representations, or otherwise.

**Comment by fleharty** [comment]
@nh13 I see, that makes sense.  Thanks!
