### ISSUE TITLE
Proposal for improvements to consensus calling

### ISSUE THREAD

**Issue by tfenne** [fulcrumgenomics/fgbio#145]
There are really three parts to this proposal:

1. Simplify the consensus caller (particularly the usage thereof) by removing parameters that we have found are not useful and are overlapped with other parameters

2. Add tags to the consensus reads that are generated so that downstream tools can know a lot more about the properties of each consensus read and it's supporting raw reads

3. Move filtering of consensus reads and bases _largely_ into a separate program that can be run after consensus calling, removing the need to call consensuses multiple times to experiment with different cutoffs

# Simplifying the consensus caller

To recap, we have a lot of parameters to consensus calling:

```scala
errorRatePreUmi: PhredScore
errorRatePostUmi: PhredScore
minInputBaseQuality: PhredScore
maxRawBaseQuality: PhredScore
rawBaseQualityShift: PhredScore
minConsensusBaseQuality: PhredScore
minReads: Int
minMeanConsensusBaseQuality: PhredScore
requireConsensusForBothPairs: Boolean
```

I'm finding that in general there are two sets of highly overlapped parameters where I favor one of the set, and would advocate for removal of the others:

1. `errorRatePostUmi`, `maxRawBaseQuality` and `rawBaseQualityShift` all work to effectively reduce the probability we construct from the raw read base qualities, albeit in slightly different ways.  I'm finding that I tend to use `errorRatePostUmi` exclusively and then set `maxRawBaseQuality` to something high that will have little to no effect, and `rawBaseQualityShift` to 0.  I propose removing `maxRawBaseQuality` and `rawBaseQualityShift`.

2. `minConsensusBaseQuality` and `minMeanConsensusBaseQuality`.  While not exactly redundant I find that I set minConsensusBaseQuality high enough (i.e. close enough to `errorRatePreUmi` that then the `minMeanConsensusBaseQuality` becomes meaningless.  I would propose getting rid of `minMeanConsensusBaseQuality`, perhaps in favor of introducing a filter on the number or proportion of no-calls generated in a consensus read (more in the filtering section).

# Adding Tags to Consensus Reads

It would help significantly to encode information about the consensus reads into tags that are added to the consensus reads in the BAM file for three reasons:

1. One could generate a single consensus BAM, re-align it, and then filter it different ways to experiment with filtering settings much more easily and quickly

2. It would allow for the information to be used in filtering variants (e.g. you could imagine a performing rank-sum based tests on things like raw-read-depth or consensus-error-rate between reads supporting ref and alt alleles at a site).

3. It would aid when manually reviewing false positive or questionable variant calls to have more knowledge about the consensus read.

The real question is what tags we should add.  We can break this down into per-read and per-base information.  My first pass is that we'd want to encode the following per read:

1. The number of raw-reads used to generate the consensus
2. The error rate of the raw-reads vs. the consensus (defined as: how many bases in raw reads disagreed with the final consensus bases, prior to masking any consensus bases for quality)

Then per-base I think we'd want to capture:

1. The number of bases contributing to the consensus as each base.
2. Either the number of disagreeing bases from the raw-reads at each base, _or_ the error rate.

This does bring up what the best way to store the per-base tags is.  The first could be stored as unsigned 8, 16 or 32 bit `int[]`s.  I'd vote for either 8 or 16 as I'm not really sure there's value in discriminating between a consensus at 256 deep vs. deeper, and definitely not between 65k deep and deeper!  The disagreeing bases could be stored in the same way, or we could store the error rates at a 32-bit `float[]` (seems overkill), or (and I'm not keen on this) do some kind of scaling/logging of the values and store them as chars.  Maybe we should test and see if using 16 or 32-bit ints has any overhead in BAM vs. 8-bit when all values are << 256?

Any other suggestions for things we definitely want to store?  I can think of some other things, but until I feel a need for them I'm tempted to stop here.

# Moving filtering into a separate program

I think this would be really beneficial for the reasons outlined above.  Obviously input-read filtering would still have to happen in consensus calling.  And I think I would like to keep a `min-reads` filter there too for efficiency sake (e.g. if you know you're never going to go below min=2 or min=3 you can save a lot of compute and filesize by enforcing that during consensus building).  But beyond that I'd suggest moving everything else off to a post-filtering tool that uses the tags described above and features of the consensus read (number of Ns, quality scores, etc.) to do both per-read and per-base filtering.

Ideally such a tool will run on an aligned BAM in coordinate order; we should discuss whether it is acceptable to produce a semi-invalid BAM (e.g. if one read in a mate is tossed, is it necessary to toss the other one too, or fix it's flags?).  If the goal is to filter before producing QC metrics and variant calls, I'm not so sure that's important.

**Comment by tfenne** [comment]
@nh13 I'd like to start in on the work described here next week.  Any chance you can take a read through this by early next week and share your thoughts?

**Comment by nh13** [comment]
For things that you want to remove, what do you think about deprecating in one commit, tagging a release, then remove in the next commit?  It may not make sense for the constructor args for the CLP classes, but definitely could be useful for the non-CLP classes (ex. `VanillaUmiConsensusCallerOptions`) as well as the methods in the CLP classes.  It's more work, but would allow folks to point to the last released version with the current API.

## Simplifying the consensus caller
1. 👍 
2. 👍 I haven't looked extensively at if errors correlate with consensus reads with higher # of Ns, but I want it to be so.  For new filters, how about adding them if we find evidence for their utility since we did a shotgun approach previously?

## Adding Tags to Consensus Reads
Agree on all fronts except where mentioned below.
- I would prefer the # of disagreeing bases as I want both error rate and the former, but only want to store one of the two in light of having the # of bases contributing to the consensus to derive one from the other.  Therefore, I would prefer the easier to store value (# of disagreeing bases and # of total bases).  Then we can just run the quick test to see the size difference between 8 and 16 bit integers.  I don't see a problem capping it at 256 (255) and saying that is `INT_MAX` for our purposes.
- I have found the minimum coverage at any base across the consensus read useful, mostly for convenience, as I have found that we may have many (>10) reads going into the consensus, but this value is low (ex. 2), and this points me towards reads where the consensus calling or other part fails after a certain point in the read.  It's a per-read tag, so should be small.
- If consensus calling from consensus calls, then I would add more tags, but we can discuss that if and when you get there.

## Moving filtering into a separate program
I am all for this.  Perhaps we have an option (to implemented later) to sanitize the output, which takes more time since it would sort by read name (or MI tag) and then reconciles the mates (based on the input options).  I think then folks could choose either to have a valid BAM (which some folks will want to give back to customers) or an intermediate for downstream purposes (ex. variant calling).

**Comment by tfenne** [comment]
Thanks for the feedback @nh13.  I'm happy to deprecate and tag, I don't think that should be much work; probably cutting the release will be most of it.  I'll get a PR ready and then we can decide if we want to do anything further before tagging and releasing.

I'm happy to go with the number of disagreeing bases in the tag.  I think the two options have equal information (given total and errors or total and error rate you can calculate the third) and you're right that integers will store more easily.  And then adding a per-read tag with the minimum depth sounds simple enough.

I like your idea of having two modes for filtering - one to create a "valid" BAM that takes longer and one that creates a "valid enough" BAM for variant calling.  I don't think it would be much more work to support both, and if not I can probably do that from the start.

**Comment by tfenne** [comment]
This is largely done bar the removal of deprecated things which will happen later.
