### ISSUE TITLE
FilterConsensusReads appears to have been removed

### ISSUE THREAD

**Issue by fleharty** [fulcrumgenomics/fgbio#216]
I believe there was a tool called FilterConsensusReads.  Is this tool still available?  Is it considered necessary when dealing with consensus reads?

**Comment by tfenne** [comment]
Hi @fleharty - yes that tool is still alive and healthy.  You can find it here:
https://github.com/fulcrumgenomics/fgbio/blob/master/src/main/scala/com/fulcrumgenomics/umi/FilterConsensusReads.scala

We think it's a fairly essential part of our toolkit for a number of reasons.  I'll try to explain, apologies for any repetition!  Our basic consensus process is:

`map -> group -> call -> remap -> filter`

Depending on the dataset, the `call -> remap` part of the process can be quite time (and space) consuming.  For that reason we have moved to performing minimal filtering during the `call` step.  The calling tools (single umi and duplex) allow filtration of the _input_ reads, and a single filter for the consensus reads - the consensus depth.  The goal of `FilterConsensusReads` is to enable rapid filtering and re-filtering of datasets.  

We find it useful to separate it because:
* For development experiments it's much more convenient to apply multiple different filters to the consensus reads after re-mapping, than to have re-run half the pipeline
* In general it allows a nice separation of concerns where we can add more filters quickly without adding to the complexity of the callers

`FilterConsensusReads` implements the following filters:
1. Min depth at both a read level and base level
2. The "consensus error rate" - i.e. the rate of disagreement between the raw reads and the called consensus - at both the read level and the base level
3. Consensus quality score at the base level
4. The maximum fraction of no-calls in a consensus read (after any masking from above)

Depending on your application you may or may not find this useful.  E.g. if your goal is to boost exome quality by building consensus reads where you can and keeping reads without duplicates, you probably won't want to filter much.  But if you have a deep-sequencing experiment you can experiment with different filtering approaches to maximize your yield of bases and minimize the number of errors that remain after filter.

**Comment by fleharty** [comment]
@tfenne Thank you very much.  This was really quite helpful to me!
