### ISSUE TITLE
Improving speed of UMI consensus generation: GroupReadsByUmi and CallMolecularConsensusReads

### ISSUE THREAD

**Issue by chapmanb** [fulcrumgenomics/fgbio#223]
Tim and Nils;
Thanks for all the work on the UMI consensus calling scripts. We're using this
in bcbio with good success and are at the point where we're trying to speed up
this part of the pipelines. We looked at some example cases and for a 7.2Gb
input BAM the initial alignment with bwa takes 3 hours, UMI consensus generation
is 3 hours and secondary alignment is a 1/2 hour:
```
Alignment 2:51 [2017-04-26T05:41Z]-[2017-04-26T08:32Z]
UMI       2:58 [2017-04-26T08:32Z]-[2017-04-26T11:30Z]
Align2    0:25 [2017-04-26T11:30Z]-[2017-04-26T11:55Z]
```
Ideally we'd like to try to speed up the UMI consensus generation to help
improve our runtimes. Currently the UMI process streams the original sorted
alignment BAM into GroupReadsByUmi, then streams that into
CallMolecularConsensusReads, then streams that output into bamtofastq
conversion.

I split the process apart and it looks like it spend an hour in GroupReadsByUmi,
half of that reading, filtering and sorting and the other half assigning and outputting:
```
fgbio GroupReadsByUmi
real    56m31.755s

[2017/05/04 10:12:08 | FgBioMain | Info] Executing GroupReadsByUmi from fgbio version 0.1.3-SNAPSHOT as kkrq359@papi on JRE 1.8.0_102-b14
[2017/05/04 10:12:08 | GroupReadsByUmi | Info] Filtering and sorting input.
[2017/05/04 10:12:19 | GroupReadsByUmi | Info] Sorted     1,000,000 record.  Elapsed time: 00:00:11s.  Time for last 1,000,000:   11s.  Last read position: chr1:11,333,904
[2017/05/04 10:36:26 | GroupReadsByUmi | Info] Sorted   117,000,000 record.  Elapsed time: 00:24:18s.  Time for last 1,000,000:   12s.  Last read position: chrX:153,184,922

[2017/05/04 10:36:35 | GroupReadsByUmi | Info] Assigning reads to UMIs and outputting.
[2017/05/04 10:36:52 | GroupReadsByUmi | Info] Output     1,000,000 record.  Elapsed time: 00:00:16s.  Time for last 1,000,000:   16s.  Last read position: chr1:11,333,861
[2017/05/04 11:08:30 | GroupReadsByUmi | Info] Output   117,000,000 record.  Elapsed time: 00:31:55s.  Time for last 1,000,000:   14s.  Last read position: chrX:153,184,911
[2017/05/04 11:08:35 | FgBioMain | Info] GroupReadsByUmi completed. Elapsed time: 56.48 minutes.
````
CallMolecularConsensusReads takes 1 1/2 hours:
```
fgbio CallMolecularConsensusReads
real    92m5.433s

[2017/05/04 11:08:38 | FgBioMain | Info] Executing CallMolecularConsensusReads from fgbio version 0.1.3-SNAPSHOT as kkrq359@papi on JRE 1.8.0_102-b14
[2017/05/04 11:08:55 | CallMolecularConsensusReads | Info] processed       500,000 record.  Elapsed time: 00:00:16s.  Time for last 500,000:   16s.  Last read position: chr1:3,416,138
[2017/05/04 12:29:10 | CallMolecularConsensusReads | Info] processed   117,000,000 record.  Elapsed time: 01:20:32s.  Time for last 500,000:   21s.  Last read position: chrX:153,184,911
[2017/05/04 12:40:42 | CallMolecularConsensusReads | Info] Total Raw Reads Considered: 117,314,724.
[2017/05/04 12:40:42 | CallMolecularConsensusReads | Info] Raw Reads Filtered Due Tag Family Min Size: 0.
[2017/05/04 12:40:42 | CallMolecularConsensusReads | Info] Raw Reads Filtered Due to Mismatching Alignments: 151,036.
[2017/05/04 12:40:42 | FgBioMain | Info] CallMolecularConsensusReads completed. Elapsed time: 92.09 minutes.
```
Do these seem like expected runtimes based on your experience? If so, do you
have any thoughts on ways we could speed up any of these steps either by
tweaking options or changing algorithms/approaches? We're happy to look at the
code ourselves and contribute if you can point us at areas you know could
benefit from optimization or multicore support. Thanks for any thoughts or suggestions.

**Comment by tfenne** [comment]
Hey Brad - I'm glad you're finding the tools useful.  We're definitely interested in speeding things up, and would love any help you're able to give.

I think the timings you're seeing are in line with what I'd expect given the inputs, calling with a min depth of 1, and inputs where there are a lot of families of sizes 1-2.  Most of our current work is focused on smaller panels at considerably higher depth, and so we tend to see that grouping takes longer than calling.

I have a bunch of thoughts as to how we could approach this:

1. My suspicion, to be validated, is that GroupReadsByUmi is dominated by a) sorting and b) writing it's output, and that CallMolecularConsensusReads is dominated by simply writing it's output.  As such it would be good to get a super high level breakdown of where the time is being spent.  More on this in a minute.
2. There are a couple of things you can try, if you're not already doing them, to speed things up somewhat - especially if you are streaming the output and not writing to disk.  We're using htsjdk under the covers, and it uses a bunch of JVM system properties to control some very useful behaviours.  The three that could help here are:
    `-Dsamjdk.use_async_io_read_samtools=true // dedicate a thread to reading the input file`
    `-Dsamjdk.use_async_io_write_samtools=true // dedicate a thread to writing the output`
    `-Dsamjdk.compression_level=0 // turn BAM GZIP compression down to 0 (or any other value)`
I would expect that turning down the compression, and possibly using async io for write, could have a significant impact on runtime.  If you're actually writing to disk then a compression level of 1 instead of 0 often offers a better trade off since you're balancing time compressing vs. time to write bytes to storage.
3. I think the first thing I would try would be to time the processes, writing to `/dev/null` with the flags turned on for zero compression and async read/write.  That'll give us an idea of how much of the time is really in the algorithm, and how much we could gain by parallelizing there.
4. Another thing I haven't tried to quantify is what the computational cost is building a "consensus" from a single read.  There is no specific handling for that case currently, so it goes through the exact same framework.  If it turns out that's expensive we could potentially add a by-pass for single reads that avoids most of the complexity and just re-emits the single read as-is.

I _think_ it would be relatively easy to introduce some parallelism in the core algorithms for both tools.  It would mostly just require some beefing up of the tests to include some at a scale where any bugs in the parallelism would come to light.  But before anyone spends effort there we should be sure that's where the effort is best spent!

The other option for speeding things up - and this would apply to many fgbio, Picard and other tools - would be to parallelize the disk-backed sorting in HTSJDK and/or parallelize the block compression for BAM files in HTSJDK.

**Comment by tfenne** [comment]
I should also mention, that if you are not using the detailed per-base tags that are generated by the consensus caller, e.g. to filter reads/bases downstream, then turning off that option (`--output-per-base-tags=false`) will reduce the size of the output significantly and thus speed things up a bit.

**Comment by tfenne** [comment]
I just tried what I suggested above on a deep dataset that I have.  Keep in mind though that this dataset goes from ~35m raw reads to only 1.8m consensus reads, so that's quite different than how I think you're using the tools.  I would expect you to see similar results to me on `GroupReadsByUmi`, but potentially much bigger improvements in `CallMolecularConsensusReads`.

Turning on async io and dropping compression to 0 improved by time for `GroupReadsByUmi` by ~35%.

Doing the same in consensus calling yielded an improvement of ~10%.

I also forgot that, by default, `CallMolecularConsensusReads` sorts it's output back into queryname order.  If you don't care about that, and are ok with reads coming out in what is approximately but not exactly coordinate order, you can add `--sort-order=unsorted`, which should speed things up by avoiding the sort.  The combination of the the suggested flags _and_ not sorting gave me a speed up of ~17%.

Obviously your results will vary based on shape of the input data and the system you're running on, but I think this shows it's worth implementing these options and then seeing if it's worth investing effort to go further.

**Comment by mjafin** [comment]
Nice improvement, thanks for looking into this so promptly. If you think that parallelisation could help we might be able to tap into the required resource (vardictjava parallelisation folks)

**Comment by chapmanb** [comment]
Tim;
Thank you so much for all the great suggestions. By implementing these IO and sorting changes, it now runs in ~2/3 the time of previously -- a fully piped run to generate gzipped fastq, equivalent to the 3 hour runtime above, now finishes in `129m18.575s`. I also tried without the final bamtofastq step and just sending the output to `/dev/null` and the timing is similar (`128m20.045s`) so we appear to have maximized what we can do with IO and any further improvements would have to be the algorithm/parallelization side.

Cutting runtimes like that is a brilliant immediate help. For anything longer term, we could explore parallelizing sections since we have multiple cores available to use. Let us know if you think anything would be a good target and we could explore that as well. Thank you again.

**Comment by tfenne** [comment]
That's great @chapmanb!  Two thoughts:

1. @nh13 has parallelized a tool quite similar to our consensus caller recently and might be able to do that here, or show the way if someone else wants to try
2. I spent some time yesterday looking at ways to improve the sorting time in `GroupReadsByUmi` and made some interesting findings.  To my surprise more time was spent reading in the BAM than was spent sorting and writing temporary files!  I think it's mostly GC overhead, and I have some ideas on how to improve that, but they're going to take me a while to implement.

**Comment by tfenne** [comment]
@chapmanb I'm closing this issue since we made some progress and it hasn't been touched in six months.  Feel free to reopen or log a new issue if you'd like to continue the conversation.
