### ISSUE TITLE
Make `SamSource` a bit friendlier and not suck up all my memory.

### ISSUE THREAD

**Issue by nh13** [fulcrumgenomics/fgbio#267]
`SamSource(input).filter { ... }.foreach { ...}` will keep all records in memory, while `SamSource(input).iterator.filter { ... }.foreach { ...}` will behave like an iterator.  This was not obvious until I ran out of memory!

**Comment by tfenne** [comment]
I'm surprised by this as the only collection type that is extended is `Iterable`, so I'd have assumed that this would implement everything via the iterator.  In poking around some more it appears to be because all of the `.filter`, `.map` etc. are expected to return an `Iterable`, and so have to generate a collection.  Ugh.  So I don't think we can fix this without some API breakage.

I think the right thing _might_ be to extend `Traversable` and then implement the `foreach` method in terms of the iterator.  Thoughts?

**Comment by tfenne** [comment]
Fixed in #307

**Comment by nh13** [comment]
https://github.com/fulcrumgenomics/fgbio/pull/307
