### ISSUE TITLE
Amplicon collapsing

### ISSUE THREAD

**Issue by abolia** [fulcrumgenomics/fgbio#270]
Hi, 

I wanted to check if fgbio can work on collapsing duplexed reads in amplicon-based NGS? Meaning Is it possible to use the tool to error correct using the duplex reads (R1 & R2) on the same amplicon, but not dedup the entire amplicon set?

Thanks,
Ashini

**Comment by nh13** [comment]
@abolia the fgbio tool `GroupReadByUmi` uses both the duplex UMIs _as well as_ the mapping information to identify reads originating from the same source molecule.  So if we have the same duplex UMIs on two read pairs, but they map to different (non-overlapping) amplicons, then there should be two consensus reads.  Are you seeing a different behavior?

**Comment by abolia** [comment]
@nh13 thanks for the reply. No, we haven't tested it yet. I just wanted to check about it before testing.  don't understand when you say "same duplex UMIs on two read pairs, but they map to different (non-overlapping) amplicons, then there should be two consensus reads". 
So, since we are talking about amplicons, the non-duplicates can also have same start and stop as they roginated from same amplicon, however unless they have same duplex UMI as well, they aren't going to be marked as duplicates. Correct?

Thanks,
Ashini

**Comment by nh13** [comment]
@abolia to be precise, we aren't detecting duplicates in the "pcr duplicates" sense, so lets talk about identifying reads from the same source molecule.  I thought you meant across two amplicons, not within an amplicon, my apologies.  If two reads have the same duplex UMI and same start/stop, then they will be treated as coming from the same duplex source molecule.   This is a big issue in general for preps like highly multiplex PCR where we do not have random starts, and the same is true for duplex sequencing if you the possible # of UMIs is small.  The alternative is to make your random UMIs longer so that two reads mapping to the same amplicon are less likely to have the same duplex UMI.  Nonetheless, I would expect this to still happen at some point in one of your amplicons due to random chance.  It will really come down to the # of amplicons, the length of your UMIs, your raw sequencing depth, and the coverage of duplexes.  It's really hard to model or predict correctly, so you may just have to perform the experiment to see what you get, and try to identify collisions between UMIs on reads mapping to the same amplicon but from different source molecules.

**Comment by abolia** [comment]
@nh13 Thanks. Actually, I wasn't really interested in duplicate removal. I understand that its not possible in amplicon sequencing, I just wanted to check if there is any way for error correction in a cluster like by using one of the subsetps used in de-duping and if fgbio tool can do that. 

Thanks.
Ashini

**Comment by nh13** [comment]
I think the hard part would be ensuring that the cluster of reads all come from the same source molecule. If so, the consensus calling should work. Otherwise true variants may be squashed by reads from a different source molecule.
