### ISSUE TITLE
SamOrder.Coordinate is not stable based on read name

### ISSUE THREAD

**Issue by nh13** [fulcrumgenomics/fgbio#275]
If two reads have the same coordinate, Picard orders the reads by:
1. read name
2. flags
3. mapq
4. mate coordinate
5. insert size

whereas fgbio orders the reads by the flags only.

There are tests where we rely on reads from the same pair are sequential if they all have the same coordinates.  @tfenne thoughts on changing the sub-sort here?

**Comment by tfenne** [comment]
@nh13 Can you remind me where we rely on reads from the same template coming together in a coordinate sorted file if they have the same coordinate?  I'm not suggesting we shouldn't do that, but I'm struggling to recall anywhere where we rely on that.

The sort keys in `SamOrder` are kept as light weight as possible so as to incurr as little memory overhead as necessary, since we keep both the key and the serialized bytes of the SamRecord in memory.  So holding on to the read name would add a non-trivial amount to memory usage.  But if we think it's necessary, then we should do it anyway.

**Comment by nh13** [comment]
I sent a Slack message in which private repo I found the test.  I also find it extremely useful when viewing a BAM to have read pairs be adjacent, especially for "unpaired" (heh) reads (i.e. read pairs where one end is unmapped).  I am happy to punt for now, but it's something to keep in the back of our minds if we see oddities like this.
