### ISSUE TITLE
Unable to run DemuxFastqs: MalformedInputException

### ISSUE THREAD

**Issue by jasonwalker80** [fulcrumgenomics/fgbio#321]
I was having issues with version 0.2.1a and 0.2.1b that are available on BioContainers. I decided to create my own docker image using 0.4.0. This is the pull request for my new Dockerfile that I'm testing
https://github.com/genome/docker-fgbio/pull/1/files

This command is not working. The error message is `Exception: MalformedInputException Error: Input length = 1`. I am having a hard time determining which input is malformed:
```
/usr/bin/java -jar /usr/fgbio/fgbio-0.4.0.jar DemuxFastqs --inputs HG00514_S1_L007_I1_001.fastq HG00514_S1_L007_R1_001.fastq HG00514_S1_L007_R2_001.fastq --metadata HG00514_unix.csv --output $PWD --read-structures 8B 16M+T +T
```

In order to upload the example data, I added a `.txt` extension to each input file:
[HG00514_unix.csv.txt](https://github.com/fulcrumgenomics/fgbio/files/1479995/HG00514_unix.csv.txt)
[HG00514_S1_L007_R2_001.fastq.txt](https://github.com/fulcrumgenomics/fgbio/files/1479996/HG00514_S1_L007_R2_001.fastq.txt)
[HG00514_S1_L007_R1_001.fastq.txt](https://github.com/fulcrumgenomics/fgbio/files/1479997/HG00514_S1_L007_R1_001.fastq.txt)
[HG00514_S1_L007_I1_001.fastq.txt](https://github.com/fulcrumgenomics/fgbio/files/1479998/HG00514_S1_L007_I1_001.fastq.txt)

FYI, there is also an ambiguous error message when the `--read-structure` argument is malformed:
`Argument could not be constructed from string`. It's a true statement, but it's unclear which argument is throwing the error.

**Comment by tfenne** [comment]
Hi @jasonwalker80 - when I run your command using fgbio-0.4.0 and your inputs I get a different error, but I wonder if the cause is the same.  I confusingly get:

```
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: Sample barcode not found in column 'Sample_Barcode' for sample id '2895564017'.
	at scala.Predef$.require(Predef.scala:277)
	at com.fulcrumgenomics.fastq.DemuxFastqs$$anon$1.<init>(DemuxFastqs.scala:103)
...
```

After much head scratching and poking at things in the debugger, it would appear to me that the problem is the encoding of the metadata file.  When I run `file HG00514_unix.csv` I get back `UTF-8 Unicode (with BOM) text`.  I'm not super familiar with handling unicode, but what seems to be happening is that the first byte/character is the BOM, but it's getting parsed as part of the "Sample_Barcode" header!

Could you try saving the metadata file in plain ASCII encoding and see if that solves your problem please?

**Comment by jasonwalker80** [comment]
UGH... sorry about that. I should have checked for special characters. 

Thanks for the quick feedback and help troubleshooting.
