### ISSUE TITLE
SampleBarcodeMetric should handle large volumes of data

### ISSUE THREAD

**Issue by nh13** [fulcrumgenomics/fgbio#369]
The `Int`s need to be `Long`.

**Comment by nh13** [comment]
@tfenne looks like there are a lot of places (ex `FastqRecord`) where we have "read number" stored as integers.  A recent experience with a NovaSeq run has made this more urgent to not have overflow.

**Comment by tfenne** [comment]
Two thoughts:

1. I'm trying to use `Metric.Count` going forward instead of `Int` or `Long` (and `Metric.Proportion` instead of `Float` or `Double`.  I think it's clearer for users (e.g. to see the type is a Count), and it's a typedef to Long so we can't forget and use Int.
2. FastqRecord's `readNumber` is meant to be 1 or 2 to indicate first or second of pair.  Unless Novaseq has some amazing new chemistry that should be ok as an `Int` 😉

**Comment by nh13** [comment]
(2) doh, that's right!
