### ISSUE TITLE
java.lang.AssertionError: assertion failed: Reads out of order

### ISSUE THREAD

**Issue by ProfessionalFarmer** [fulcrumgenomics/fgbio#416]
Hi, dear developers.
I met some error when using fgbio's GroupReadsByUmi. It prompted that reads out of order. Even I processed data by Picard's RevertSam with SANITIZE=true and all the REMOVE/RESTORE options set to false, the error still exist.

Exception in thread "main" java.lang.AssertionError: assertion failed: Reads out of order @ M4988:25:000000000-G244L:1:2103:19288:2268/2 + M4988:25:000000000-G244L:1:2101:2860:20442/2
        at scala.Predef$.assert(Predef.scala:219)
        at com.fulcrumgenomics.umi.GroupReadsByUmi.$anonfun$execute$16(GroupReadsByUmi.scala:486)
        at com.fulcrumgenomics.umi.GroupReadsByUmi.$anonfun$execute$16$adapted(GroupReadsByUmi.scala:485)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at com.fulcrumgenomics.umi.GroupReadsByUmi.execute(GroupReadsByUmi.scala:485)
        at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:99)
        at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:80)
        at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:48)
        at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)

The reads information in bam as bellow:
M4988:25:000000000-G244L:1:2103:19288:2268     99      chr1    50269493        60      149M    =       50269623 279     TTCCTGCCTAACAGATCTTAAAATAAAGACCCAAAAGGATCAAAATGTTTCCAAGTAACTTAACTGCATCCCAGAACAAATCTCAAGAATACTTAAAGAAATATAAAAATATCCAGCTCCAAACAAGGTAAAATTCACAATGTCTGGAA    CCCFFFFFFFGCGGGGGGGGHHHHHHHHGHHHHHHHGGHHHHHHHHHHHHGHHHHFGHIHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGHHHHHHHHFGHHHHHHHHHGHHGHHHHHH     MC:Z:149M       MD:Z:0A148      RG:Z:HD779-1-1  MI:Z:ATTC       NM:i:1  MQ:i:60 UQ:i:34 AS:i:148XS:i:32  RX:Z:ATTC

M4988:25:000000000-G244L:1:2103:19288:2268     1171    chr1    50269623        60      149M    =       50269493 -279    AAATTCACAATATCTGGAATTCAGTCAAAAACTACAAAGCATGTAAAAATGCAGAAAAATAGGACCCACATTGAGAAGACGCATATTCATTAGGAACTGAAACAGATATTAGAATTAGGAAATATAGACAATAAATAGTTATGACTGTA    >>>2DF>BB>11@1F1DBB111B1FEB2FBF22@FHHGBHG@HGFD22FD12GHGFHHF2GHGA/12F2GF2FF2/EAAA22HGF1FAA12FG2HHDBHHHGAGFEAGDEGDFFDFGFGBHFBHFFFFGGDGFFGGBEGF3F1@FF>1>     MC:Z:149M       MD:Z:11G88C48   RG:Z:HD779-1-1  MI:Z:ATGC       NM:i:2  MQ:i:60 UQ:i:55 AS:i:139XS:i:22  RX:Z:ATTC

M4988:25:000000000-G244L:1:2101:2860:20442     1123    chr1    50269493        60      149M    =       50269623 279     TTCCTGCCTAACAGATCTTAAAATAAAGACCCAAAAGGATCAAAATGTTTCCAAGTAACTTAACTGCATCCCAGAACAAATCTCAAGAATACTTAAAGAAATATAAAAATATCCAGCTCCAAACAAGGTAAAATTCACAATGTCTGGAA    BBBFFBFFFFGGGGGGGGGGHHGHHHHFFHFHEEHHGGHFFFEGHHHHHHEGHHFBFFHHHHGFFFFFHHFHGF1FGFCFGHHHFDEFGFHGHHHGHH5GHHGFHHGHGGHHHHHHHHGHHHHHHHGHHHHHHHGGFGHHHHFHHHGFH     MC:Z:149M       MD:Z:0A148      RG:Z:HD779-1-1  MI:Z:ATTC       NM:i:1  MQ:i:60 UQ:i:33 AS:i:148XS:i:32  RX:Z:ATGC

M4988:25:000000000-G244L:1:2101:2860:20442     147     chr1    50269623        60      149M    =       50269493 -279    AAATTCACAATGTCTGGAATTCAGTCAAAAACTACAAAGCATGTAAAAATGCAGAAAAATAGGACCCACATTGAGAAGACGCATATTCATTAGGAACTGAAACAGATATTAGAATTAGGAAATATAGACAATAAATAGTTATGACTGTA    HGF4HHHHHEHGHGHHHHGHGGHHGGGHHFHHHHHHHGHHHHHHFHHHHHHHHHHHFHFHFHHEGHHHHHHHHHHGGGGGHFHHGEFHGHGGGHHFGHHHFGGDHHHHHHHHBHHFGBFGFHHHHHFGHGGGFGFCGGGFFFFBFFABB     MC:Z:149M       MD:Z:100C48     RG:Z:HD779-1-1  MI:Z:ATGC       NM:i:1  MQ:i:60 UQ:i:37 AS:i:144XS:i:22  RX:Z:ATGC

All I noticed was that they have the same position. Dose this affect? 
I am appreciated for any help. Thanks a lot.

**Comment by nh13** [comment]
Can you post your full command line you used for `GroupReadsByUmi`?  Similar to #413, you may be using using `--raw-tag MI` rather than `--raw-tag RX`.  I suspect this since the MI tag for `M4988:25:000000000-G244L:1:2103:19288:2268` is `ATTC` for read one and `ATGC` for read two, indicating the reads from the same pair are not from the same source molecule.  Some upstream tool is adding the `MI` tag, for example Picard's `UmiAwareMarkDuplicatesWithMateCigar`.  You might try adding `MI` to the `ATTRIBUTE_TO_CLEAR` option in `RevertSam` too.

Also, it would be good for us to know which upstream tool set the `MI` tag for you, so that we can contact the authors/developers too!  It also helps us debug future issues.

**Comment by nh13** [comment]
@ProfessionalFarmer since now we have had a few folks use `--raw-tag MI`, I'd like to understand the original reasoning for using the `MI` tag as input to `GroupReadsByUmi` so we can provide better documentation, work with the Picard developers (I used to be one), or something else.  Hopefully you are willing to share.
