### ISSUE TITLE
Ion Torrent Reads -  Annotate and split bams

### ISSUE THREAD

**Issue by davidroberson** [fulcrumgenomics/fgbio#420]
Hello,

We have developed an assay at NCI that has dual indexes on Ion Torrent (believe it or not).  We will publish soon.  We let the torrent sever and TMAP do its thing with the first index.  We would like to use this tool to grab the 3' index.  I am currently doing it a different way but I have a feeling this tool will be more efficient computationally.  We require exact matches and the assay efficiency is very adequate.  

We would like to send the results filtered bams through TVC next.  Are ```AnnotateBamWithUmis``` and ```ExtractUmisFromBam``` the correct functions to start with?

Thank you and sorry for the random question.  We will site this tool in the paper if it works out.

**Comment by nh13** [comment]
@davidroberson are the indexes sample barcodes or molecular identifiers?  Could you tell us a little more about the read structure?

If you want to perform sample demultiplexing with the 3' index (or both), use `DemuxFastqs`.  You can set the read structure appropriately to identify which bases are barcodes and which are template on the 3' end due to indel errors.

If you have molecular identifiers, so use  `AnnotateBamWithUmis or `ExtractUmisFromBam` depending on the input data.  For the latter, if you have a fixed set of molecular identifiers (rather than random), you can also run `CorrectUmis` after extracting the UMIs from the read.

**Comment by davidroberson** [comment]
@nh13 

They are indexes but we want TMAP to operate as normal can just soft clip them out.  We then filter for reads that are full length all the way to the Ion adapter.  TMAP hard clips the Ion Adapter and adds a bam tag indicating the read made it to the end.

Doing it this way allows the torrent server to do the analysis.  We then have a plugin which will do the rest on the torrent server. 

https://github.com/fulcrumgenomics/fgbio/issues/136

So based on the read structure of inline barcodes I will use ```ExtractUmisFromBam```.  My understanding is that ```AnnotateBamWithUmis``` are when the UMIs are on separate reads from the template reads (i.e. Illumina)?

BTW, we have an Illumina MiSeq version of this assay that I will be able to use this for as well.  The barcodes are also inline.

**Comment by nh13** [comment]
`ExtractUmisFromBam` will work well for your case then, as long as the _target sequence_ has fixed length (no indels from the sequencer [Ion Torrent]).  I'd also be concerned about using reads where the adapter is not found.  Again, if you have a fixed set of _amplicon barcodes_ use `CorrectUmis` after `ExtractUmisFromBam` to assign them correctly.
