### ISSUE TITLE
GroupReadsByUmi non-pf-reads question

### ISSUE THREAD

**Issue by sheenams** [fulcrumgenomics/fgbio#428]
If I set '--include-non-pf-reads=true', will that allow reads in which only one end mapped to be included in the output? I'm trying to identify gene fusions in paired-end UMI data. The docs say:

Reads are aggressively filtered out so that only high quality read pairs with both ends mapped are taken forward. 

But it isn't clear to me what 'filters' are defined as in the case of 'include-non-pf-reads'.

**Comment by nh13** [comment]
The `--include-non-pf-reads` option applies to only reads where the 'pass-filter' flag has been set on the record (see the `0x200` value in the FLAG section 1.4.2 in the [SAM Spec](https://samtools.github.io/hts-specs/SAMv1.pdf)).

At this time, it is hard-coded to remove read pairs where one end is unmapped.  This is because we rely on finding the span (start & end) of the template (aka product), where R1 is on one end and R2 is on the other.  Having one end mapped would stop us from finding one of the ends of the template.

You might want to check out Picard's `UmiAwareMarkDuplicatesWithMateCigar` tool, though I am not sure if it does exactly what you want.
