### ISSUE TITLE
RX tag question

### ISSUE THREAD

**Issue by ggydush** [fulcrumgenomics/fgbio#431]
Would it be possible to shed some light on how molecular consensus and duplex consensus RX tags are added?

I have an example where reads from GroupReadsByUmi show 3 possible RX tags (expected): 
`java -jar $FGBIO GroupReadsByUmi -i test.bam -o test_grouped.bam -s Paired`
```
RX:Z:AGT-GTT
RX:Z:GTT-AGT
RX:Z:TGT-GTT
```

After CallMolecularConsensusReads, the consensus reads have the following RX tags (expected):
`java -jar $FGBIO CallMolecularConsensusReads -i test_grouped.bam -o test_ssc.bam -M 1`
```
RX:Z:GTT-AGT
RX:Z:AGT-GTT
```

After CallDuplexConsensusReads, the duplexes have the following RX tags (unexpected):
`java -jar $FGBIO CallDuplexConsensusReads -i test_grouped.bam -o test_dsc.bam`
```
RX:Z:GGT-GTT
```

As the majority of reads have the RX tag `AGT-GTT`, I was expecting the output from CallDuplexConsensusReads to have the same. Example BAMs were sent via email. Thanks in advance!

**Comment by nh13** [comment]
@ggydush sorry for the delay.  I don't think there's a bug, just a misunderstanding between `MI` and `RX`.

`GroupReadsByUmi` stores the _unique molecular identifier_ in the `MI` tag, not the `RX` tag.  Since  `RX:Z:AGT-GTT` and `RX:Z:TGT-GTT` are only one edit away, I would suspect they have the same `MI` value.  Both `CallMolecularConsensusReads` and `CallDuplexConsensusReads` use the `MI` values to group reads.

Looking at the example you sent me, I see two `MI` values in your grouped BAM:  `MI:Z:0/A` (26 records) and `MI:Z:0/B` (34) records.  Since this is duplex data, looking good so far.

When running `CallMolecularConsensusReads`, we should see two consensus pairs (4 records total), one for `0/A` and one for `0/B`.  This is as you stated above.  The `RX` value stored for each read/record (4 of them) is the _consensus_ of the `RX` values for the input raw reads.

When running `CallDuplexConsensusReads `, we should see one read pair (4 records) total, since there was only one molecule (i.e. with identifer`0`), that was observed on both strands (`/A` and `/B`). See the wiki [1](https://github.com/fulcrumgenomics/fgbio/wiki/Developer-Note:-Tracking-Reads-through-Grouping-and-Duplex-Consensus-Calling) and [2](https://github.com/fulcrumgenomics/fgbio/wiki/Calling-Duplex-Consensus-Reads) for a better explanation.  If examine the `MI` tags of the duplex consensus reads (R1 and R2), they now have the same value (`0`).  The `RX` is again the consensus `RX` value across the input reads.

**Comment by ggydush** [comment]
Thank you for the explanation! I'm still confused how the final duplex UMI is `RX:Z:GGT-GTT` when there are no reads that contain `GGT` in their RX tag. I would epect the duplex RX tag to be `AGT-GTT`. Is the consensus RX tag formed without flipping the RX tags so they are in the same order?

```
Is this how consensus molecules are made?

RX:Z:GTT-AGT (top)
RX:Z:AGT-GTT (bottom)
     GGT-GTT (G from top, G from bottom, T from either, - GTT from bottom)

Rather than this?

RX:Z:GTT-AGT (top)
RX:Z:GTT-AGT (bottom, switched to match orientations)
     GTT-AGT
```


Apologies if I'm missing something.

**Comment by nh13** [comment]
No apologies necessary.  I think your right in spotting a bug: https://github.com/fulcrumgenomics/fgbio/pull/489
