### ISSUE TITLE
Can CallDuplexConsensusReads keep mapping position?

### ISSUE THREAD

**Issue by rebber** [fulcrumgenomics/fgbio#461]
Hi,

I'm wondering whether output of CallDuplexConsensusReads can keep the mapping position from the grouped bam instead of being unmapped bam? If not, what is the reason?

Don't we loose some evidence of correct mapping by re-mapping the consensus reads? My reasoning is that if we have multiple reads from the same fragment (i.e. same UMI) mapping on the same position, that is strong evidence for the mapping to be correct. But after consensus read calling, all those have been condensed to one read, and after re-mapping that consensus read we won't have as strong evidence that it's position is correct, since it's only one read. Does that make sense?

/Rebecka

**Comment by nh13** [comment]
We unmap the reads as the consensus may be different than the raw reads used to create the consensus.  Furthermore, this allows us not to worry about combining cigars (especially when they differ among the raw reads). Re-mapping is a conservative approach.

It is an interesting idea to assert that having multiple raw reads from the same fragment map to the same position should bolster the confidence (i.e mapping quality) of that mapping.  I think there would need to be some more thought here, since if the raw reads all had the same base sequence, they don't confer any different information, while if all the raw reads had different base sequences, then they would.  In the former case, I'd argue that confidence in mapping location is bolstered, while in the latter, I'd be open to thinking about it.  We'd also have to solve if the raw reads map to the same place, but differently (indels).

Therefore, mapping the consensus reads is required.  It shouldn't be too onerous, since the # of consensus reads is far smaller than the # of raw reads.
