### ISSUE TITLE
Non-unique duplexes near repetitive regions

### ISSUE THREAD

**Issue by ggydush** [fulcrumgenomics/fgbio#491]
We have found what appears to be a single duplex consensus molecule duplicated when the end of fragment lies in a homopolymer region. We are still unsure of the exact mechanism (polymerase slippage during PCR, sequencing error, etc.), but it has lead to false duplex depth and duplication of mutant molecules.

I've attached a screenshot showing an example where there are 6 duplex molecules all with the same UMI (`CCT-AAC`), same start position, but varying stop position. With the complexity of our libraries, we believe these molecules are most likely artifact. The screenshot shows another example (UMI: `CTC-GCC`) and I've found a handful of other cases like it - all with fragments ending in a repetitive region.

We were thinking of incorporating a post-consensus filter to account for this, but wanted to check in with you guys to see if you had seen this before.

![example](https://user-images.githubusercontent.com/35151789/59795443-466a2300-92a9-11e9-9977-c0882e0e4112.png)

**Comment by nh13** [comment]
If you look at the start of the reads in sequencing orientation (i.e. the first base sequenced) on the right most reads, they are mapped to the reverse strand, so the right-most bases are the first bases sequenced.  It looks like the right-most reads start in a homopolymer of significant length (ex 9+ bases), which is a known error mode of Illumina sequencing.  I am surprised the quality _after_ the long homopolymer is so high.  Since we group reads by start position (both ends of a pair), they aren't grouped together as one molecule, but instead six as you see.  You can confirm this by looking at the molecular identifier tag in the grouped reads.

It would be interesting to allow some wiggle room for the start of the alignment when grouping reads, but this would have to be done on a case-by-case basis, since we have to balance correctly grouping reads with spuriously grouping reads, with the latter more likely when there are fewer possible UMIs, greater depth, and so on.  You could certainly post-process either the grouped BAM or the consensus BAM to fix these up or filter them out.  I'd be interested in what you choose, as I could see you extending an existing tool or contributing a new one to fgbio to handle this.
