### ISSUE TITLE
How to set --read-structure using +T 9M+T?

### ISSUE THREAD

**Issue by cxue** [fulcrumgenomics/fgbio#498]
I have a 9-bp UMI in R2 files. I'd like to extract UMI using: 
java -Xmx200g -Djava.io.tmpdir=`pwd`/tmp -jar $FGBIO ExtractUmisFromBam \
--input=../call/$SAMPLE.uBAM.bam \
--output=../call/$SAMPLE.umi.uBAM.bam \
--read-structure=+T 9M+T \
--single-tag=RX \
--molecular-index-tags=ZA ZB

But I got the error message:
Exception: ValidationException
Error: Either a single SAM tag, or the same # of SAM tags as molecular indices in the read structure,  must be given.

This read structure is validated by https://fulcrumgenomics.github.io/fgbio/validate-read-structure.html. What;s wrong with this command?

thanks

**Comment by tfenne** [comment]
Hi @cxue the problem is that the total number of molecular barcodes in your read structures is 1 (i.e. `+T` contains zero and `9M+T` contains one), but the number of tags in which to store molecular indices given is two (`--molecular-index-tags=ZA ZB`).  The message is trying to tell you that either a) those counts need to match or b) you can always specify just one tag, and all the UMIs will be concatenated into that tag.

So try dropping the `ZB` and it should work.

**Comment by cxue** [comment]
Hi, Tim,
      Thank you for much for kindly help! I got it.

      best
     Cheng

Tim Fennell <notifications@github.com> 于2019年6月27日周四 上午7:21写道：
