### ISSUE TITLE
Read structure with variable skip base length

### ISSUE THREAD

**Issue by Emmalynchen** [fulcrumgenomics/fgbio#510]
I've tagged my molecules with the ThruPLEX Tag-seq kit (library structure below), done targeted 150bp PE sequencing, and was wondering how I should treat the variable 8-11nt stem that comes after UMI1 and UMI2.

![Screen Shot 2019-07-25 at 9 39 00 AM](https://user-images.githubusercontent.com/11758684/61892314-600e1400-aec0-11e9-925d-826f3e302c29.png)

I'm currently skipping 8nt and assuming the adapter sequence before the UMIs are removed during demultiplexing to generate the fastq files for each sample. Does this look right?

java -Djava.io.tmpdir=/scratch -jar fgbio.jar FastqToBam \
--input R1.fastq.gz R2.fastq.gz \
--read-structures 6M8S+T 6M8S+T \
--sort TRUE

Also, is there enough information to use CallDuplexConsensusReads or only CallMolecularConsensusReads?

**Comment by nh13** [comment]
@Emmalynchen to be honest, since you don't actually know the length of the variable sequence in each read (even with alignment to a reference, you can have the last 1-3 bases randomly match the reference), I would recommend trimming 11bp after UMI1/UMI2.  Yes, you'll invariably lose a few extra bases that _could have been_ part of the insert, but at least you won't randomly call parts of the stem as part of the insert. Does that make sense to you?

**Comment by Emmalynchen** [comment]
Yes, that makes sense. So it's better to trim the additional bases, even if that means trimming bases that are part of the template, to ensure that when there are bases that aren't part of the template they're not used for incorrect alignment.
