### ISSUE TITLE
why CorrectUmis increases the size of the bam file 9fold

### ISSUE THREAD

**Issue by naumenko-sa** [fulcrumgenomics/fgbio#538]
Hello, fgbio developers!

Thanks for the great suit of tools to work with UMIs!

I've noticed that when correcting UMIs against the pre-defined while list, the resulting bam file is huge. My input was 36G, after correction with 

```
fgbio -Xms750m -Xmx30g -XX:+UseSerialGC --tmp-dir . \
--async-io=true --compression=0 \
CorrectUmis \
-t XC -m 3 -d 1 -x -U /path/umi.whitelist.txt \
-i samplex-sort.bam \
-o samplex-sort-umis_corrected.bam
```
samplex-sort-umis_corrected.bam is 332G. 

When I sorted it after fgbio with:
```
cat samplex-sort-umis_corrected.bam | \
bamsormadup tmpfile=file.tmp inputformat=bam threads=16 \
outputformat=bam level=0 SO=coordinate > \
samplex-sort-umis_corrected.sorted.bam
```
the file size reduced not so much: 311G

Could you please explain, why CorrectUmis step increases the bam file size and whether it is possible to reduce it?

Sergey

**Comment by tfenne** [comment]
Hi @naumenko-sa - is you input BAM file compressed?  My guess would be that it is, and that your output BAM file is not since I see `-compression=0` in your command.  I would suggest two things:

1. Try dropping that argument to go back to the default compression level (or if you're worried about speed, keep it and pipe into `samtools view` or `sambamba view` to compress).
2. Try running `samtools view $file | wc` on both the input and output BAMs.  This will tell you the uncompressed size of each and make it clear whether compression is the issue.

CorrectUmis doesn't not add much extra information to the BAM.  There's no reason the BAM should grow by more than a tiny fraction if all other things are equal (i.e. compression level, sort order, etc.).

**Comment by naumenko-sa** [comment]
Hi Tim @tfenne!
Thanks, the default compression with `fgbio ... | samtools view -bh > output.bam` helped.
SN
