### ISSUE TITLE
ClipBam causing strand bias 

### ISSUE THREAD

**Issue by Lewis-Gallagher** [fulcrumgenomics/fgbio#567]
Hi all,

I have been using fgbio a while and have been using it for a number of our lab's cfdna analyses.  My concern is that the ClipBam function might be causing some strand bias when it comes to variant calls.  

I have a purchased cell line with a spiked in variant at 5%.  After aligning, grouping, calling concensus reads and aligning those concensus reads I clip the over lapping reads prior to variant calling with:
```
java -jar fgbio-0.6.1.jar ClipBam \
    -i bam \
    -o sort.bam \
    -m clipbam.metrics \
    -r ref_fasta \
    --clip-overlapping-reads=true \
    -c Hard 
```

And I end up with a 2:1 strand-bias in the bam

<img width="338" alt="image" src="https://user-images.githubusercontent.com/38728190/74521699-bf417d80-4f11-11ea-8fc6-7f8a5e489cf4.png">

Compared with the same sample but without ClipBam

<img width="305" alt="image" src="https://user-images.githubusercontent.com/38728190/74521821-f4e66680-4f11-11ea-9803-3f05e4adf972.png">

If there is a variant on both strands, how does ClipBam decide which starnd to keep the variant on?

Any help would be really appreciated.

Thanks

Lewis

**Comment by tfenne** [comment]
@Lewis-Gallagher Looking at the code what you're suggesting seems quite possible, especially if  the assay you're using is multiplexed-PCR or something similar where you have amplicons with fixed start/end positions.  ClipBam clips overlapping reads by clipping the ends of both R1 and R2 approximately equally until the overlap is eliminated, so that at least in shotgun data it does not introduce any R1/R2 bias or strand bias.  

However if you have fixed-ends with the variant closer to one end than the other (as almost all variants would be) then that will always result in the read that covers the variant earlier in the read retaining coverage of the variant.  Is this what's happening in your case?  I'm not really sure what to do about that since it's not really different than if you designed an amplicon with the variant in a position where it would only be covered by R1/R2.

Lastly, looking at your image I would not call the _variant_ strand biased.  The _coverage_ is.  All strand bias tests I'm aware of are formulated as some kind of different of proportion test that ask whether the proportion of F reads carrying the variant is significantly different from the proportion of R reads.  In your case you have F=55/(55+1077)=0.486 and R=100/(100+1922)=0.495 which looks pretty good.

**Comment by Lewis-Gallagher** [comment]
@tfenne Thanks for the quick response.  

> Looking at the code what you're suggesting seems quite possible, especially if the assay you're using is multiplexed-PCR or something similar where you have amplicons with fixed start/end positions

Yes, we are using a targeted amplicon panel here for multiplexed cfDNA analysis. 

> However if you have fixed-ends with the variant closer to one end than the other (as almost all variants would be) then that will always result in the read that covers the variant earlier in the read retaining coverage of the variant. Is this what's happening in your case? 

From looking at the un-clipped bam, I can see that most reads overlap almost entierly. So that is probably the reason I'm seeing reasonably balanced coverage of both strands. 

<img width="2372" alt="image" src="https://user-images.githubusercontent.com/38728190/74536342-cecfbf00-4f2f-11ea-98c6-928c9506feed.png">


> I'm not really sure what to do about that since it's not really different than if you designed an amplicon with the variant in a position where it would only be covered by R1/R2.

So if I understand correctly, the strand inconsistencies I'm seeing exist due to the variant falling more often on one end of the read than the other? This wouldn't necceserily be a bias generated by the software, just a stochastic process?


> Lastly, looking at your image I would not call the variant strand biased. The coverage is.

This is actally a very good point and it didn't occur to me to think of it this way, thank you!

**Comment by Lewis-Gallagher** [comment]
@tfenne Hi, have just spoken to the researcher and it's a hybridisation capture panel, not amplicon like I initially said.  Which makes it a bit more confusing as the coverage should be more uniform, no?

**Comment by nh13** [comment]
The [screenshot in your last comment](https://github.com/fulcrumgenomics/fgbio/issues/567#issuecomment-586305043) is telling.  Since it is hybrid capture, the probe is likely in the middle of that coverage distribution, and so we get reads more often around the probe, with coverage falling off as we get farther from the probe.  Since the variant is on one side of the probe, we still get bias as to where it lands relative to top-strand/bottom-strand in a read pair.  Namely, it looks to me like the variant more often falls close to the end of the top-strand read, while falls close to the start of the bottom-strand read.  So when we clip them evenly back, we end up keeping the variant in the bottom strand read more often.  So even if it is hybrid-selection, the bias remains.

A potential solution would be instead of trimming back each read in a pair equally, randomly pick one and trim it all the way back.

**Comment by Lewis-Gallagher** [comment]
Thanks @nh13 ! I guess it explains it a bit, though I do see that in the middle of exons as well, which in theory shouldn't be affected by this. But then these might be due to pure chance, when we are talking about a few reads

**Comment by PedalheadPHX** [comment]
exome capture does create a strand bias on the edge of the two edges capture target, so if your variant is to one side of the capture targets you can see a strand coverage bias. For specific targets you can avoid this is capture design by increasing the capture window so the edge bias of the capture is outside your area of interest
