### ISSUE TITLE
Raw Reads Filtered Due to Insufficient Support

### ISSUE THREAD

**Issue by gevro** [fulcrumgenomics/fgbio#661]
Hi, What is the exact definition of this metric for CallMolecularConsensusReads?

Thanks.

**Comment by nh13** [comment]
There are two places where we filter out reads due to insufficient support.

The first (1) place ([here](https://github.com/fulcrumgenomics/fgbio/blob/57988d615fa6188e0028faedfdf65ed13cf645e7/src/main/scala/com/fulcrumgenomics/umi/VanillaUmiConsensusCaller.scala#L156)) does not call a consensus if there are fewer than the minimum # of raw reads for a group of reads (eg. `--min-reads` in `CallMolecularConsensusReads`).

The second (2) place ([here](https://github.com/fulcrumgenomics/fgbio/blob/57988d615fa6188e0028faedfdf65ed13cf645e7/src/main/scala/com/fulcrumgenomics/umi/VanillaUmiConsensusCaller.scala#L172)  does the same, but **after** some filtering to ensure the raw reads have the "same" alignment structure.  The process for determining that is explained in more [detail in the duplex caller description on our wiki](https://github.com/fulcrumgenomics/fgbio/wiki/Calling-Duplex-Consensus-Reads#cigar-filtering), but it applies here as well.  This step is done to ensure that reads are not "out of phase" with each other due to indel errors, which can happen particularly in low complexity regions and around STRs (PCR stutter).

**Comment by gevro** [comment]
Thanks for explaining. Regarding filtering out 'out of phase' alignments, you mention that you do not create multi-alignments (or local reassembly) of all the reads within a UMI group: "Since we do not generate a multiple-alignment of all raw reads to each other".

I'm just curious is this because this is too computationally expensive?

**Comment by nh13** [comment]
It is more computationally expensive, but there are a number of multiple-alignment libraries that are _very_ fast.  In fact, to investigate if multi-alignment could help, I wrote a little tool [`callerpp`](https://github.com/nh13/callerpp) to allow the consensus caller to pipe data for partial alignments and read them back in.  It really didn't help, except for STRs, which is why I even looked since I was trying to call the CODIS STRs.
