### ISSUE TITLE
tumor and normal both used umi

### ISSUE THREAD

**Issue by asmlgkj** [fulcrumgenomics/fgbio#741]
Dear professor,
Thanks a lot for developing such a powerful tool for umi treated data
If tumor and paired normal sample both used umi , when use vardict for calling data, should I used the fgbio treated normal sample or just sorted_dedup.bam

model1
tumor_fgbio.bam    vs       normal_fgbio.bam

<br>
<br>
model2  
tumor_fgbio.bam    vs       normal_sorted_dedup.bam

**Comment by nh13** [comment]
Can you provide more context about what you're trying to accomplish (specificity, sensitivity, low frequency variant detection, etc. etc)?  Can you tell us how the UMIs are treated?  In general, we're happy to help with the downstream use of our tools with more context. 

If there is an issue or question with a specific `fgbio` tool feel free to re-open this issue, otherwise I suggest you move over to more general forums like https://www.biostars.org/.

**Comment by asmlgkj** [comment]
yes, both the normal and tumor sample add umi when sequencing, umi is 3M2S+T in both reads,
Thanks a lot
