### ISSUE TITLE
Error in FilterConsensusReads 

### ISSUE THREAD

**Issue by dstephensSD** [fulcrumgenomics/fgbio#858]
I get the same error as #847 while using v2.0.2

![image](https://user-images.githubusercontent.com/103445628/178973639-a797291b-26b7-42f7-ad61-e9220ecec5a8.png)

Code:
```
        fgbio -Xmx16g --async-io FilterConsensusReads  \
            -Djava.io.tmpdir=tmp  \
            --input=input  \
            --output=output  \
            --ref=ref \
            --min-reads=0 0 0 \
            --max-read-error-rate=0.05  \
            --max-base-error-rate=0.1  \
            --min-base-quality=50  \
            --max-no-call-fraction=0.05  \
            --require-single-strand-agreement=true
```

How the input to the above was generated:
```
        fgbio -Xmx16g --async-io CallDuplexConsensusReads  \
            -Djava.io.tmpdir=tmp  \
            --input=input  \
            --output=output  \
            --error-rate-pre-umi=45  \
            --error-rate-post-umi=30  \
            --min-input-base-quality=30
```
Also occurs with --min-reads=1 0 0

Here is that read:

![image](https://user-images.githubusercontent.com/103445628/178976444-a7183d42-4d5d-4f08-8b75-82b18252d7d2.png)

**Comment by nh13** [comment]
Interesting! Any chance you can share the the input to `CallDuplexConsensusReads` for the reads with that UMI?  I'd like to debug how the consensus reads are called, to give the error in filtering.

**Comment by nh13** [comment]
I am also curious what you're doing to have 3bp reads!

**Comment by nh13** [comment]
Alternatively, could you test out your data on: https://github.com/fulcrumgenomics/fgbio/pull/859?

**Comment by dstephensSD** [comment]
Here are a few reads that can be input to CallDuplexConsensusReads which will generate the 3bp read from above.

[test_sorted.txt](https://github.com/fulcrumgenomics/fgbio/files/9189400/test_sorted.txt)

Thanks!

**Comment by nh13** [comment]
This is a really insidious scenario.

First, the insert size for the raw reads are reported as `3`.  Taking a look at the reads, these are FR pairs, where the start of R1 is almost at the end of R2.  For one read pair, R1 maps to `498924-499063` on the positive strand while R2 maps to  `498784-498926` on the negative strand.  So R1's start position is just two bases before the end of R2.  For FR pairs, we do trim reads back based on if they ["map past the end of the mate"](https://github.com/fulcrumgenomics/fgbio/blob/74d920e4c45623f337eac3fd4f2892b68f90776c/src/main/scala/com/fulcrumgenomics/umi/UmiConsensusCaller.scala#L255).  So in this case, these reads are trimmed to just 3bp long!

Now, there are four read pairs in your input test case.  Three are FR pairs, while one is strictly not (`A01801:9:H7YJGDMXY:1:1428:4318:3208`).  The trimming above applies just to FR pairs, so the latter read is full length.  R2 does have low quality bases, so it's first three bases are masked as Ns.  It's the only "AB R2"  (see how we [track and label AB and BA](https://github.com/fulcrumgenomics/fgbio/wiki/Developer-Note:-Tracking-Reads-through-Grouping-and-Duplex-Consensus-Calling)), so its consensus depth is zero and its consensus bases are all Ns.

Now we create thee R2 duplex consensus read, which is created from the AB R2 and BA R1 single strand consensus reads, trimming to the shorter length of the two (three bases!).  The AB strand depth gets annotated as zero, while the BA strand depth gets annotated as three (`aD` and `bD` tags respectively in the R2 output duplex consensus read).  The output bases are N in this case, since the consensus calls where not high enough quality (one strand had an N!).

So we end up with a consensus read (R2) with AB depth of zero.

Then we pass this into FilterConsensusReads where it always assumes that if BA depth is non-zero, that AB depth is also non-zero.

I _think_ the correct solution is that when the AB strand has depth zero and the BA strand has depth > 0, we should create a single strand consensus from the BA strand and swap the labels.  We already do that if only one strand was observed: https://github.com/fulcrumgenomics/fgbio/blob/74d920e4c45623f337eac3fd4f2892b68f90776c/src/main/scala/com/fulcrumgenomics/umi/DuplexConsensusCaller.scala#L344-L345

@tfenne thoughts?

**Comment by nh13** [comment]
@dstephensSD check out #864
