### ISSUE TITLE
CallMolecularConsensusReads `--min-reads `

### ISSUE THREAD

**Issue by migrau** [fulcrumgenomics/fgbio#874]
First time working with UMIs, so probably it is very basic question.
About the `--min-reads` parameter of CallMolecularConsensusReads:

`--min-reads The minimum number of reads to produce a consensus base.`

In the previous step (GroupReadsByUmi), it groups reads together that appear to have come from the same original molecule. So `--min-reads` (CallMolecularConsensusReads) it's creating a single fragment consensus from all the PCR duplicates from the same original molecule and the same read end position? Because without PCR duplicates, all the positions are covered only by a single read per UMI, right?

**Comment by nh13** [comment]
Reads that are identified by GroupReadsByUmi as from the same source molecule (MI tag) can be fed into consensus calling (CallMolecularConsensusReads or CallDuplexConsensusReads) to create a single best guess at the bases from the source molecule.  The usage of `--min-reads` in `CallMolecularConsensusReads` affects both the results and run time.  From the usage:

>Particular attention should be paid to setting the --min-reads parameter as this can have a dramatic effect on both results and runtime. For libraries with low duplication rates (e.g. 100-300X exomes libraries) in which it is desirable to retain singleton reads while making consensus reads from sets of duplicates, --min-reads=1 is appropriate. For libraries with high duplication rates where it is desirable to only produce consensus reads supported by 2+ reads to allow error correction, --min-reads=2 or higher is appropriate. After generation, consensus reads can be further filtered using the FilterConsensusReads tool. As such it is always safe to run with --min-reads=1 and filter later, but filtering at this step can improve performance significantly.

**Comment by nh13** [comment]
Note: the duplicate flag on the SAM file is not set by any of these tools.  You do not need to mark duplicates since the consensus calling step outputs a single consensus read for each family of "duplicates" (or more accurately, for each set of reads identified as originating from the same source molecule)


Reads grouped together by `GroupReadsByUmi` (i.e. have the same MI) have the same outer start/stop.  The mapping coordinates and the UMI are used to group reads together.  Take a close read of: https://pubmed.ncbi.nlm.nih.gov/28100584/.

You can track a family by inspecting the `MI` SAM tag.  The raw reads out of GroupReadsByUmi will have them, and then the consensus read from `CallMolecularConsensusReads`, and so on.  The consensus read may be re-aligned to a different region altogether, and some consensus reads are likely filtered out by `FilterConsensusReads`.   Hopefully this can help you understand the data flow.
