### ISSUE TITLE
Is CallDuplexConsensusReads supposed to outputs reads as unmapped bam?

### ISSUE THREAD

**Issue by karlbeutner** [fulcrumgenomics/fgbio#896]
Hello, The output I am getting `fromCallDuplexConsensusReads` has no @SQ tags in the header, and no mapping info (rname, flags, cigar, etc) in the reads. I don't see anywhere in the documentation where the output is described as either aligned, or unaligned so it is hard for me to know if this is the expected result. I assumed the mapping info could/would be inferred from the component reads - but it does not look like this is the case. 

Is there a way to run this command so that the output includes alignment information for the consensus reads?

**Comment by nh13** [comment]
@karlbeutner that's a good point about the docs not saying the consensus reads produced _do not_ have mapping information. You can check out our best-practice recommendations here: https://github.com/fulcrumgenomics/fgbio/blob/main/docs/best-practice-consensus-pipeline.md, where you'll see that one needs to re-align the data after calling consensus reads.

**Comment by nh13** [comment]
Not implemented, and hard.

**Comment by karlbeutner** [comment]
Can you elaborate on what makes it hard, @nh13?

I can think of two approaches for doing this. I would like to hear what makes this hard so that I can think through how/if the approaches I have in mind address what you have already identified as the major challenge(s).

**Comment by nh13** [comment]
It’s a lot of book-keeping so hard in practice not in theory. And then all the SAM tags, and what about secondary and supplementary alignments. 

And since the number of consensus reads are typically much smaller than the raw reads, asking folks to re-align the consensus reads isn’t onerous. So I don’t think this is low hanging fruit.  

Closing this thread as I believe the original question has been answered.
