### ISSUE TITLE
BWA mem -Y did not make a difference in consensus calling

### ISSUE THREAD

**Issue by esamorodnitsky** [fulcrumgenomics/fgbio#901]
In the best practices document, it was suggested for both times that BWA mem is to be run to include the -Y flag. I tried running a bunch of my samples with BWA mem with  and without -Y flag. The final md5sums of my final consensus BAM files came out to be the same with or without the flag.

**Comment by nh13** [comment]
It's most crucial at the following steps:
* https://github.com/fulcrumgenomics/fgbio/blob/main/docs/best-practice-consensus-pipeline.md#step-2a2-consensus-ubam---consensus-mapped-bam
* https://github.com/fulcrumgenomics/fgbio/blob/main/docs/best-practice-consensus-pipeline.md#step-2b2-consensus-filtered-ubam---consensus-mapped--filtered-bam

It affects the SAM tags, ensuring that the per-base tag values are maintained in the same order as the read bases/qualities (they should be the same length too, please verify).  Please make sure you used `fgbio ZipperBams` so that the SAM tags in the input BAM to `bwa mem` are carried forward into the mapped BAM.
