### ISSUE TITLE
The range of the value in step fgbio FilterConsensusReads

### ISSUE THREAD

**Issue by Xiangnyu** [fulcrumgenomics/fgbio#930]
Hello, can anyone tell me the range of these four parameters ''min-reads'', ''max-read-error-rate'', 'max-base-error-rate', and 'max-no-call-fraction' in FilterConsensusReads, respectively. Many thanks!

**Comment by kockan** [comment]
Devs can correct me if I'm wrong but it looks like there's no upper limit for min-reads other than the fact that it's an `Int`, and for the others, it looks like the accepted range is [0,1] based on the snippet below:

```
if (maxReadErrorRate.exists(e => e < 0 || e > 1)) fail("max-read-error-rate must be between 0 and 1.")
if (maxBaseErrorRate.exists(e => e < 0 || e > 1)) fail("max-base-error-rate must be between 0 and 1.")
if (maxNoCallFraction < 0 || maxNoCallFraction > 1) fail("max-no-call-fraction must be between 0 and 1.")
```

**Comment by nh13** [comment]
`FilterConsensusReads` is very much dependent on your objections filtering the consensus reads, either to be very restrictive to all the way to no filters at all.  They should set based on your specific data via controls.  They are left to the user to specify due to how specific they are to your data and desired outcome.  Feel free to share what data you're filtering and what you're optimizing for, though it is a non-trivial project beyond the scope of the issue to examine the data and set those, so I am closing for now.  Feel free to reach out to us if you want to inquire about paid support.

**Comment by Xiangnyu** [comment]
Thanks for your replys, I just tried different value in my data, which I found max-read-error-rate=0.05 filter out more consensus reads than  max-read-error-rate=0.025, it's wired. Well, the min-reads value in CallMolecularConsensusReads step is the most important one for the final clean consensus reads. May be the parameter of min-reads=2 is suitable for low VAF, right?
