### ISSUE TITLE
bug: the logic for the PileupBuilder `includeMapPositionsOutsideFrInsert` filter is wrong

### ISSUE THREAD

**Issue by jrm5100** [fulcrumgenomics/fgbio#980]
`positionIsOutsideFrInsert` is actually `positionIsInsideFrInsert`

https://github.com/fulcrumgenomics/fgbio/blob/3a74fd28ff630b417410953541ff107a1b7b0fb7/src/main/scala/com/fulcrumgenomics/bam/pileup/PileupBuilder.scala#L123-L128

The filter is used in a way that is reversed so that the current tests still work as designed.

https://github.com/fulcrumgenomics/fgbio/blob/3a74fd28ff630b417410953541ff107a1b7b0fb7/src/main/scala/com/fulcrumgenomics/bam/pileup/PileupBuilder.scala#L203-L205

Additionally there is a redundant `rec.isFrPair` call (this is done inside the method).

I came across this because I was tracking down some aberrant alleles in a pileup. Should reads mapped to separate chromosomes be rejected by this filter, or should that be a separate filter (likely in `quickAcceptRecord`)?  Currently these are accepted even if `includeMapPositionsOutsideFrInsert` is `false`, which i think may be misleading.

**Comment by clintval** [comment]
I confirm:

1. The private`positionIsOutsideFrInsert` was actually `positionIsInsideFrInsert`
2. Despite (1), the use of `positionIsOutsideFrInsert` was still correct in function
3. The additional `rec.isFrPair` was unnecessary and created unintuitive behavior

Check out #981. I can't assign you as a reviewer, but would like your 👀 on it.

**Comment by clintval** [comment]
The history of the filter started 5 years ago in the context of somatic variant filtration:

https://github.com/fulcrumgenomics/fgbio/blob/ff43d10d5443874504632f6af2b27f6c7e0f23c2/src/main/scala/com/fulcrumgenomics/vcf/filtration/FilterSomaticVcf.scala#L140-L166

It was then refactored into the PileupBuilder and swapped from a negative filter (`exclude`) to a positive filter (`include`):

- https://github.com/fulcrumgenomics/fgbio/pull/763#discussion_r794482862

The filter still _behaves_ correctly:

| Action | Behavior |
| --- | --- |
| True | Do not apply the filter. |
| False | Remove FR pairs where the position in that pair is _**outside**_ the insert coordinates. Otherwise keep the record (single-end, RF pair, tandem pair). |

Because of this semantic change, the [`includeMapPositionsOutsideFrInsert`](https://github.com/fulcrumgenomics/fgbio/blob/3a74fd28ff630b417410953541ff107a1b7b0fb7/src/main/scala/com/fulcrumgenomics/bam/pileup/PileupBuilder.scala#L65) filter behaves correctly but it's meaning might be unclear. Why would someone want to include map positions _**outside**_ the FR pair? I now think the filter should behave exactly as it is now but be called:

- `includeMapPositionsInsideFrInsert`

And its default set to `true`.

**Comment by clintval** [comment]
What do you think of renaming [`includeMapPositionsOutsideFrInsert`](https://github.com/fulcrumgenomics/fgbio/blob/3a74fd28ff630b417410953541ff107a1b7b0fb7/src/main/scala/com/fulcrumgenomics/bam/pileup/PileupBuilder.scala#L65) to `includeMapPositionsInsideFrInsert` and swapping the default boolean from `false` to `true`? It would be a breaking Scala API change, but gratefully the name change would require a developer who is using it to reconsider the filter when updating their use of the API.

**Comment by clintval** [comment]
@jrm5100 I don't think we want to exclude records where the mate maps to a different reference sequence since although they are not a proper pair, they should still count towards coverage when requesting to pile up reads at a position. But if you do not want to include them, you can add a custom filter like:

```scala
PileupBuilder(source).withReadFilter(rec => rec.refName == rec.mateRefName)
```

**Comment by clintval** [comment]
Yes, this was the original intent of the filter:

> Keep those not isFrPair but when they are isFrPair, make sure they aren't outside the insert region

So I need to revert the change I just made and update the documentation to be more clear. The original `rec.isFrPair` wasn't redundant! I've just gotten myself confused along the way.
